# Generated by Django 4.0.5 on 2022-06-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades_alter_persona_options_persona_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'Programador'), ('4', 'Desarrollador')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
